server:
  port: 9001
spring:
  cloud:
    nacos:
      discovery:
        # 指向nacos服务端
        server-addr: 127.0.0.1:8848
  application:
    # 在spring cloud alibaba微服务框架中
    # web应用的该属性,就会被当成一个服务名称来使用
    # 如果业务功能不同,服务名称 值也要不同
    name: luban-demo-cart
  profiles:
    active: local
