#server:
#  port: 9003
#spring:
#  application:
#    name: luban-demo-order
#  profiles:
#    active: local
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
rocketmq:
  name-server: localhost:9876
  producer:
    group: luban-demo-order

user:
  enable: true
spring:
  cloud:
    sentinel:
      datasource:
        "nacos-degrade-rules":
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            data-id: degradeRules.json
            rule-type: degrade