#server:
#  port: 9003
#spring:
#  application:
#    name: luban-demo-order
#  profiles:
#    active: local
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848


user:
  enable: true